import { v4 as uuidv4 } from 'uuid';

export const dataArray = [
  {
    name: 'Владимир',
    surname: 'Ульянов',
    patronymic: 'Ильич',
    birthday: '02.02.1993',
    id: uuidv4(),
  },
  {
    name: 'Олег',
    surname: 'Иванов',
    patronymic: 'Александрович',
    birthday: '04.02.1996',
    id: uuidv4(),
  },
  {
    name: 'Алексей',
    surname: 'Смирнов',
    patronymic: 'Алексеевич',
    birthday: '13.03.1997',
    id: uuidv4(),
  },
  {
    name: 'Александр',
    surname: 'Кузнецов',
    patronymic: 'Данилович',
    birthday: '12.04.1994',
    id: uuidv4(),
  },
  {
    name: 'Роман',
    surname: 'Попов',
    patronymic: 'Павлович',
    birthday: '15.05.1993',
    id: uuidv4(),
  },
  {
    name: 'Константин',
    surname: 'Васильев',
    patronymic: 'Робертович',
    birthday: '01.06.1992',
    id: uuidv4(),
  },
  {
    name: 'Павел',
    surname: 'Петров',
    patronymic: 'Ефимович',
    birthday: '02.07.1988',
    id: uuidv4(),
  },
  {
    name: 'Геннадий',
    surname: 'Соколов',
    patronymic: 'Иваныч',
    birthday: '03.08.1983',
    id: uuidv4(),
  },
  {
    name: 'Руслан',
    surname: 'Михайлов',
    patronymic: 'Бедросович',
    birthday: '04.09.1985',
    id: uuidv4(),
  },
  {
    name: 'Алик',
    surname: 'Харитонов',
    patronymic: 'Викторович',
    birthday: '05.10.1977',
    id: uuidv4(),
  },
  {
    name: 'Вячеслав',
    surname: 'Козлов',
    patronymic: 'Владимирович',
    birthday: '06.11.1998',
    id: uuidv4(),
  },
  {
    name: 'Сергей',
    surname: 'Новиков',
    patronymic: 'Вольфович',
    birthday: '07.12.1994',
    id: uuidv4(),
  },
  {
    name: 'Игорь',
    surname: 'Морозов',
    patronymic: 'Георгиевич',
    birthday: '08.12.1992',
    id: uuidv4(),
  },
  {
    name: 'Ильяс',
    surname: 'Петров',
    patronymic: 'Геннадиевич',
    birthday: '09.11.1974',
    id: uuidv4(),
  },
  {
    name: 'Амир',
    surname: 'Волков',
    patronymic: 'Максимович',
    birthday: '10.10.1982',
    id: uuidv4(),
  },
  {
    name: 'Ренат',
    surname: 'Зайцев',
    patronymic: 'Львович',
    birthday: '11.09.1983',
    id: uuidv4(),
  },
  {
    name: 'Степан',
    surname: 'Павлов',
    patronymic: 'Леонидович',
    birthday: '12.08.1967',
    id: uuidv4(),
  },
  {
    name: 'Владимир',
    surname: 'Семёнов',
    patronymic: 'Константинович',
    birthday: '13.07.2004',
    id: uuidv4(),
  },
  {
    name: 'Максим',
    surname: 'Богданов',
    patronymic: 'Кириллович',
    birthday: '14.06.2005',
    id: uuidv4(),
  },
  {
    name: 'Алексей',
    surname: 'Воробьёв',
    patronymic: 'Исаакович',
    birthday: '15.05.2001',
    id: uuidv4(),
  },
  {
    name: 'Александр',
    surname: 'Беляев',
    patronymic: 'Тарасович',
    birthday: '16.04.2003',
    id: uuidv4(),
  },
  {
    name: 'Роман',
    surname: 'Тарасов',
    patronymic: 'Степанович',
    birthday: '17.03.1967',
    id: uuidv4(),
  },
  {
    name: 'Константин',
    surname: 'Комаров',
    patronymic: 'Ярославович',
    birthday: '18.02.1957',
    id: uuidv4(),
  },
  {
    name: 'Павел',
    surname: 'Орлов',
    patronymic: 'Юрьевич',
    birthday: '19.01.1974',
    id: uuidv4(),
  },
  {
    name: 'Геннадий',
    surname: 'Андреев',
    patronymic: 'Романович',
    birthday: '20.02.1987',
    id: uuidv4(),
  },
];
